### ISSUE TITLE
[Bug] out 폴더 인식 불가 문제

### ISSUE THREAD

**Issue by JaeHunLee-git** [1-Chic-Choc/sivillage-backend#42]
### 🐛 버그 설명
- Dto, Vo 폴더 안의 out 폴더를 인식하지 못함

###  🔍 버그 확인 방법
- .gitignore 파일에 기본 설정으로 out 폴더가 들어가있음

###  🎯 기대 동작 및 해결 방법(선택)
- .gitignore에 next.js의 ignore 조건인 "out"이 들어가있었음

**Comment by SeongGwangJu** [comment]
👍
